workspace:
  base: /go
  path: src/github.com/papillonyi/thor

pipeline:
  build:
    image: golang
    environment:
    - GO111MODULE: on
    - GOPROXY: https://goproxy.io

    commands:
    - CGO_ENABLED=0 go build -tags netgo -a -v -o thor cmd/*
  publish:
    image: plugins/docker
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/thor
    username: andyi@live.cn
    password: 123456Y
    registry: registry-vpc.cn-shanghai.aliyuncs.com
    tag:
    - latest
    - ${DRONE_BUILD_NUMBER}

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://kubernetes.default.svc.cluster.local
    kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4temdzbGgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQyMzc3MzQ3LTBlZmYtMTFlOS1iNmM0LTAwMTYzZTFhY2Y5MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.B8hsTxwZObNrOViz_IofQDDqgSMo1P8rHo-xy-h5c1n2l_SDF7Ysricriq1szXKCNh3ZUfSYhKOEeudS2jUqg1cBAfkK27jYhefcdB3wOfl76cyik-J5eaUC-3_YWyJX7c6Zgw8cYDs4DDA-LnwDSD1opFkpNeSvAnfG6ZrmFLDQUPVeN8_uVF-mnkeD9MdSjOg-1NWZ0u3PPLoGJkaGLrwgNf8RB850NiYDSyFPI3ZO1uE5r8d-JlL_wpQSKaviKiTc_lbpDkxzbQ3gB9hERF2oYgTY_dnTzdEjmVa0wSm52HPQ_Xvg1fIw7EF0hcztGD7mfFfbxelCDM-RJtBxdg
    deployment: thor
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/thor
    container: thor
    tag: ${DRONE_BUILD_NUMBER}
