workspace:
  base: /go
  path: src/github.com/papillonyi/thor

pipeline:
  build:
    image: golang
    commands:
    - CGO_ENABLED=0 go build -tags netgo -a -v -o thor cmd/*
  publish:
    image: plugins/docker
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/thor
    username: andyi@live.cn
    password: 123456Y
    registry: registry-vpc.cn-shanghai.aliyuncs.com
    tag:
    - latest
    - ${DRONE_BUILD_NUMBER}

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://kubernetes.default.svc.cluster.local
    kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkcm9uZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTd2eHIyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJiODYzNTdjMC0wZjM5LTExZTktYjZjNC0wMDE2M2UxYWNmOTEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZHJvbmU6ZGVmYXVsdCJ9.puBJHgH4oK3eiB9Z-3kCVcQT5Yc5X7nHbX3fOmoutv4gfPgoe9w5Zn0AGe_EcU9XEM_K-Tt4QWskXsLktoiySMR_ueeRbFx7y04bkW3HuHATJb_Bnbv65OIAqU7EvfJfsyIwOIn_mQNzKLEoDpuTZbfIHIyouEtkuG_Yw7PWeLWoktK2_vY3y7-Tkm5FFZGrmP8ivxeeKEWqtnDJNYc460uAZbMhnA4SHt0EUotaFYvX_KEIpc8m4fmigfZAv9pn6ACZv8K2BR4wkWZ40RLPicOsYIGbc5yXAJ9Jq5yymOs57l_rfDtaFf0IxYPmMnioi8btHVi-VhQ83LUc9qlruQ
    deployment: thor
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/thor
    container: thor
    tag: ${DRONE_BUILD_NUMBER}
