workspace:
  base: /go
  path: src/github.com/papillonyi/thor

pipeline:
  build:
    image: golang
    commands:
    - CGO_ENABLED=0 go build -tags netgo -a -v -o thor cmd/*
  publish:
    image: plugins/docker
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/thor
    username: andyi@live.cn
    password: 123456Y
    registry: registry-vpc.cn-shanghai.aliyuncs.com
    tag:
    - latest
    - ${DRONE_BUILD_NUMBER}
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://kubernetes
    deployment: thor
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/thor
    container: thor
    tag: ${DRONE_BUILD_NUMBER}
